# Generated by Django 4.2.19 on 2025-11-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama_openedx_backend', '0004_dashboard_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardtype',
            name='student_view',
            field=models.BooleanField(default=False, help_text="If enabled, these dashboards will be made available to students. Important: these dashboards must include the parameters 'userId' and 'lms', have filters applying these parameters to all visuals, and the dashboard must be shared disabling users to access any filter.", verbose_name='Available to students'),
        ),
    ]
