# Generated by Django 4.2.11 on 2026-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama_openedx_backend', '0005_dashboardtype_student_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccessconfiguration',
            name='arn',
            field=models.CharField(blank=True, default='', help_text='Quicksight user ARN', max_length=255, null=True, verbose_name='ARN'),
        ),
    ]
